project:
  type: website
  output-dir: docs

website:
  title: "Elias Dewald"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - Projects.qmd
      - Resume.qmd
      - Hobbies.qmd
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

