project:
  type: website
  output-dir: docs

website:
  title: "Elias Dewald"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: Projects.qmd
        text: Projects
      - href: Resume.qmd
        text: Resume
      - href: Hobbies.qmd
        text: Hobbies
      

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

